version: "3.9"

services:
  web:
    build:
      context: .
    container_name: frontend_eletronica
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      - DJANGO_DOCKER=1
      - DEBUG=False
      - API_URL=http://backend:8000  # o nome 'backend' resolve na rede compartilhada
    networks:
      - eletrorapida_net

networks:
  eletrorapida_net:
    external: true
